### ISSUE TITLE
TI from array

### ISSUE THREAD

**Issue by p-ortega** [JuliaEarth/ImageQuilting.jl#53]
Hi!

This is more of a question than an issue. I have a TI that is basically a 3D array. 

There is any way to use it as it is in the IQ solver? 

My current workaround is to save it as a GSLIB and then load it again, but it seems inefficient. 

Thanks!

**Comment by juliohm** [comment]
> This is more of a question than an issue. I have a TI that is basically a 3D array.

Feel free to join our community channel: https://juliaearth.github.io/GeoStats.jl/stable/about/community.html

> There is any way to use it as it is in the IQ solver?

We need to georeference the array into a coordinate system first. This is done with the `georef` function:

```julia
georef((property=array,))
```

Take a look in the official docs: https://juliaearth.github.io/GeoStats.jl/stable/data.html
